#!/usr/bin/env python
# -*- coding: utf-8 ^*-

import unittest
from dbUtil import dbUtil
import pymysql

class test_dbUtil(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_connect001(self):
        expected = pymysql.connection()
        actual = dbUtil.connect()
        self.assertEqual(ecpcted, actual)

if __name__ == '__main__':

    unittest.main()
